apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myappdeve-4dea"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myappdeve-4dea"
  template:
    metadata:
      labels:
        app: "myappdeve-4dea"
    spec:
      containers:
        - name: "myappdeve-4dea"
          image: "dinbtechitregistry.azurecr.io/myappdeve"
          ports:
          - containerPort: 80