apiVersion : apps/v1
kind: Deployment
metadata:
  name: "instapieaks-b4b7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "instapieaks-b4b7"
  template:
    metadata:
      labels:
        app: "instapieaks-b4b7"
    spec:
      containers:
        - name: "instapieaks-b4b7"
          image: "dinbtechit.azurecr.io/instapieaks"
          ports:
          - containerPort: 80