apiVersion: v1
kind: Service
metadata:
    name: "intapieaks-99aa"
    labels:
        app: "intapieaks-99aa"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "intapieaks-99aa"