apiVersion: v1
kind: Service
metadata:
    name: "myappdeve-4dea"
    labels:
        app: "myappdeve-4dea"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myappdeve-4dea"